# Generated by Django 3.0.8 on 2020-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleDeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Number', models.CharField(max_length=200)),
                ('Full_Names', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TitleDeeds',
        ),
    ]
