# Generated by Django 3.0.8 on 2020-09-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansystem', '0002_auto_20200916_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledeed',
            name='Title_Image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
