# Generated by Django 3.0.8 on 2020-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansystem', '0003_titledeed_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titledeed',
            name='Title_Image',
            field=models.ImageField(default='images', upload_to='images/'),
        ),
    ]
